# Generated by Django 4.0.3 on 2022-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='E-mail')),
                ('horario_atendimento', models.TextField(blank=True, verbose_name='Horário de atendimento')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebok')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('telefone', models.CharField(blank=True, max_length=32, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=32, verbose_name='Celular')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
                'ordering': ['razao_social'],
            },
        ),
    ]
