# Generated by Django 4.0.3 on 2022-03-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CortesCabelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('baixo_degrade', 'Baixo degrade'), ('media_degrade', 'Médio degrade'), ('alto_degrade', 'Alto degrade')], max_length=50, verbose_name='Modelo')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia')),
            ],
        ),
    ]
