# Generated by Django 4.0.3 on 2022-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0002_cortescabelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortescabelo',
            name='foto',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
