# Generated by Django 4.0.3 on 2022-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0003_cortescabelo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortescabelo',
            name='descricao',
            field=models.CharField(default=1, max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
