# Generated by Django 4.0.3 on 2022-04-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('duracao', models.CharField(choices=[('1', '00:30'), ('2', '01:00'), ('3', '01:30'), ('4', '02:00')], max_length=50, verbose_name='Duração')),
                ('preco', models.FloatField(verbose_name='Preço')),
            ],
        ),
    ]
