# Generated by Django 4.0.3 on 2022-04-18 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='nome',
            field=models.CharField(choices=[('corte', 'Corte'), ('barba', 'Barba'), ('sobrancelha', 'Sobrancelha'), ('corte_sobrancelha', 'Corte e sobrancelha'), ('corte_barba', 'Corte e barba'), ('barba_sobrancelha', 'Barba e Sobrancelha'), ('corte_barba_sobrancelha', 'Corte,barba e sobrancelha')], max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='preco',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço'),
        ),
    ]
