# Generated by Django 4.0.3 on 2022-05-23 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_corte_nome_alter_corte_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('corte', 'Corte'), ('barba', 'Barba'), ('sobrancelha', 'Sobrancelha'), ('corte_sobrancelha', 'Corte e sobrancelha'), ('corte_barba', 'Corte e barba'), ('barba_sobrancelha', 'Barba e sobrancelha'), ('corte_barba_sobrancelha', 'Corte, barba e sobrancelha')], max_length=255, verbose_name='Nome')),
                ('duracao', models.CharField(choices=[('1', '00:30'), ('2', '01:00'), ('3', '01:30'), ('4', '02:00')], max_length=50, verbose_name='Duração')),
                ('preco', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço')),
            ],
        ),
        migrations.DeleteModel(
            name='Corte',
        ),
    ]
