# Generated by Django 4.0.3 on 2022-05-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tipocorte_delete_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(max_length=255, verbose_name='Cliente')),
                ('horario', models.DateTimeField(verbose_name='Horário')),
                ('tipo_corte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tipocorte')),
            ],
        ),
    ]
