# Generated by Django 4.0.3 on 2022-05-24 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_corte_observacao_corte_status_tipocorte_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corte',
            name='observacao',
            field=models.TextField(default=str, max_length=200, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('efetuado', 'Efetuado'), ('cancelado', 'Cancelado')], default='agendado', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tipocorte',
            name='duracao',
            field=models.SmallIntegerField(choices=[(1, '00:30'), (2, '01:00'), (3, '01:30'), (4, '02:00')], verbose_name='Duração'),
        ),
    ]
