# Generated by Django 4.0.3 on 2022-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_corte_cliente_alter_corte_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corte',
            name='tipo_corte',
        ),
        migrations.AddField(
            model_name='corte',
            name='duracao',
            field=models.SmallIntegerField(choices=[(1, '00:30'), (2, '01:00'), (3, '01:30'), (4, '02:00')], default=1, verbose_name='Duração'),
            preserve_default=False,
        ),
    ]
